#include "wifi_manager.h"

#include "esp_log.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_netif.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "csi_manager.h"
#include "udp_receiver.h"

#define WIFI_SSID      CONFIG_WIFI_SSID
#define WIFI_PASSWORD  CONFIG_WIFI_PASSWORD

static const char *TAG = "wifi_manager";

/*
 * Starts the sensing pipeline after Wi-Fi connection is established.
 *
 * A short delay is used because the station may receive an IP address before
 * the Wi-Fi driver is fully ready for CSI configuration.
 */
static void sensing_start_task(void *pvParameters)
{
    vTaskDelay(pdMS_TO_TICKS(1000));

    /*
     * Enable CSI collection before starting the UDP receiver.
     * The UDP traffic generated by the AP will then produce CSI samples.
     */
    csi_manager_start();

    /*
     * Starts a UDP socket that receives packets from the AP controller.
     * These packets create controlled Wi-Fi traffic for CSI sensing.
     */
    udp_receiver_start();

    /*
     * This task is only needed during initialization, so it deletes itself.
     */
    vTaskDelete(NULL);
}

/*
 * Handles Wi-Fi and IP events.
 *
 * ESP-IDF uses an event-driven model. Instead of blocking and waiting for
 * connection states, the Wi-Fi driver notifies this handler when something
 * relevant happens.
 */
static void wifi_event_handler(
    void *arg,
    esp_event_base_t event_base,
    int32_t event_id,
    void *event_data
)
{
    /*
     * The station interface has started. At this point, the ESP32-S3 can
     * begin trying to connect to the configured AP.
     */
    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START) {
        ESP_LOGI(TAG, "Trying to connect to the access point...");
        esp_wifi_connect();
    }

    /*
     * If the connection drops, reconnect automatically.
     * CSI is also marked as disabled so it can be reconfigured later.
     */
    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {
        ESP_LOGW(TAG, "Disconnected from AP. Reconnecting...");
        csi_manager_reset();
        esp_wifi_connect();
    }

    /*
     * The station received an IP address from the AP.
     * This means the Wi-Fi connection is ready for the sensing pipeline.
     */
    if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        ip_event_got_ip_t *event = (ip_event_got_ip_t *) event_data;

        ESP_LOGI(TAG, "Connected to AP");
        ESP_LOGI(TAG, "Assigned IP: " IPSTR, IP2STR(&event->ip_info.ip));

        /*
         * Start CSI and UDP reception in a separate task.
         * This avoids doing heavier initialization directly inside the
         * event handler.
         */
        xTaskCreate(
            sensing_start_task,
            "sensing_start_task",
            4096,
            NULL,
            5,
            NULL
        );
    }
}

/*
 * Initializes the ESP32-S3 as a Wi-Fi station.
 *
 * In this project, the station is the sensing node. It connects to the AP
 * controller and receives controlled Wi-Fi packets used for CSI extraction.
 */
void wifi_manager_start(void)
{
    /*
     * Initializes the TCP/IP network stack abstraction used by ESP-IDF.
     */
    ESP_ERROR_CHECK(esp_netif_init());

    /*
     * Creates the default event loop required by Wi-Fi and IP events.
     */
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /*
     * Creates the default network interface for station mode.
     */
    esp_netif_create_default_wifi_sta();

    /*
     * Initializes the Wi-Fi driver using the default configuration.
     */
    wifi_init_config_t wifi_init_config = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&wifi_init_config));

    /*
     * Registers the same handler for Wi-Fi events and IP events.
     */
    ESP_ERROR_CHECK(esp_event_handler_register(
        WIFI_EVENT,
        ESP_EVENT_ANY_ID,
        &wifi_event_handler,
        NULL
    ));

    ESP_ERROR_CHECK(esp_event_handler_register(
        IP_EVENT,
        IP_EVENT_STA_GOT_IP,
        &wifi_event_handler,
        NULL
    ));

    /*
     * Wi-Fi credentials are read from menuconfig through CONFIG_* macros.
     * This avoids hardcoding credentials directly in the source code.
     */
    wifi_config_t wifi_config = {
        .sta = {
            .ssid = WIFI_SSID,
            .password = WIFI_PASSWORD,
        },
    };

    /*
     * Sets Wi-Fi mode to station, applies the configuration, and starts Wi-Fi.
     */
    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());

    /*
    * Disable Wi-Fi power saving during CSI acquisition.
    *
    * This keeps the radio continuously active and helps maintain a more
    * regular packet reception rate.
    */
    ESP_ERROR_CHECK(esp_wifi_set_ps(WIFI_PS_NONE));

    ESP_LOGI(
        TAG,
        "Wi-Fi station started with power saving disabled"
    );
}