"""
Feature Extraction

This module converts CSI windows into numerical feature vectors that can
be used by machine learning algorithms.

Input:

    window[packet][subcarrier]

Output:

    features[feature_index]

Instead of feeding the classifier with the raw CSI signal, a set of
statistical descriptors is extracted from each subcarrier.

Current features:

    mean
    standard deviation
    minimum
    maximum
    peak-to-peak
    energy

These features summarize the behavior of a subcarrier within a window,
reducing the amount of data while preserving relevant information about
presence and movement.

Pipeline position:

    sliding window
    ↓
    feature extraction
    ↓
    Fisher Score
    ↓
    decision tree
    
The selected features were intentionally chosen because they are
computationally inexpensive and can be efficiently implemented in
embedded systems such as the ESP32-S3.
"""

from core_math import mean, std, get_column


def minimum(values):
    """
    Compute the minimum value of a signal.

    Formula:

        min(X)

    The minimum represents the lowest amplitude observed during the
    window and may capture local signal attenuation events caused by
    human presence or movement.
    """
    if not values:
        return 0.0

    min_value = values[0]

    for value in values:
        if value < min_value:
            min_value = value

    return min_value


def maximum(values):
    """
    Compute the maximum value of a signal.

    Formula:

        max(X)

    The maximum represents the highest amplitude observed during the
    window and may capture peaks generated by channel variations.
    """
    
    if not values:
        return 0.0

    max_value = values[0]

    for value in values:
        if value > max_value:
            max_value = value

    return max_value


def energy(values):
    """
    Compute the signal energy.

    Formula:

        Energy = Σ Xi²

    where:

        Xi = signal sample

    Energy measures the overall signal magnitude accumulated throughout
    the window.

    Larger values indicate stronger overall signal activity, while
    smaller values indicate a more stable or weaker signal.
    """
    total = 0.0

    for value in values:
        total += value * value

    return total


def extract_features_from_window(window):
    """
    Extract statistical features from a CSI window.

    Input:

        window[packet][subcarrier]

    Output:

        features[feature_index]

    For each subcarrier, the following descriptors are extracted:

        mean
        standard deviation
        minimum
        maximum
        peak-to-peak
        energy

    Peak-to-peak is computed as:

        peak_to_peak = max(X) - min(X)

    Example:

        31 subcarriers
        6 features per subcarrier

        total_features = 31 × 6 = 186

    The resulting feature vector becomes the input to the feature
    selection and classification stages.
    """

    features = []

    if not window:
        return features

    num_subcarriers = len(window[0])

    for sc in range(num_subcarriers):
        signal = get_column(window, sc)

        min_value = minimum(signal)
        max_value = maximum(signal)

        features.append(mean(signal))
        features.append(std(signal))
        features.append(min_value)
        features.append(max_value)
        features.append(max_value - min_value)
        features.append(energy(signal))

    return features


def extract_features_from_labeled_window(labeled_window):
    """
    Convert a labeled CSI window into a labeled feature vector.

    The class label is preserved while the raw signal window is replaced
    by its extracted statistical descriptors.

    Input:

        {
            "label": class_name,
            "data": window
        }

    Output:

        {
            "label": class_name,
            "features": [...]
        }

    This format is used throughout the supervised learning stages of the
    project.
    """

    return {
        "label": labeled_window["label"],
        "features": extract_features_from_window(
            labeled_window["data"]
        ),
    }


def extract_feature_dataset(labeled_windows):
    """
    Convert a complete window dataset into a feature dataset.

    Each window is independently transformed into its corresponding
    feature vector.

    The resulting dataset is the main input for:

        - Fisher Score ranking
        - Feature selection
        - Decision tree training

    This stage represents the transition from signal processing to
    machine learning.
    """

    dataset = []

    for labeled_window in labeled_windows:
        item = extract_features_from_labeled_window(
            labeled_window
        )

        dataset.append(item)

    return dataset

