from __future__ import annotations

"""
Small grid search for the temporal state machine.

The development CSV may be used to choose parameters, but the selected
configuration must later be evaluated on a different continuous scenario.

The grid includes a raw-equivalent baseline:
* no smoothing;
* zero startup discard;
* one confirmation for every transition;
* minimum probability 0.0 for every transition.

Therefore, the best result found by this script cannot be worse than the raw
classifier accuracy on the same development CSV.
"""

import argparse
import copy
import csv
import json
import sys
from pathlib import Path
from typing import Any, Mapping, Sequence

THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[2]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from Tools.realtime.temporal_state_machine import (  # noqa: E402
    DEFAULT_CONFIG,
    TemporalStateMachine,
    process_rows,
)


SMOOTHING_OPTIONS: dict[str, list[float]] = {
    "none": [1.0],
    "light_2": [0.20, 0.80],
    "light_3": [0.10, 0.20, 0.70],
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def write_csv(path: Path, rows: Sequence[Mapping[str, Any]]) -> None:
    if not rows:
        raise ValueError("No tuning rows to save.")

    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys())

    with path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def valid_expected_rows(
    rows: Sequence[Mapping[str, Any]],
    minimum_purity: float,
) -> list[Mapping[str, Any]]:
    valid_labels = {"empty", "static_presence", "movement"}
    return [
        row
        for row in rows
        if str(row.get("expected_label", "")) in valid_labels
        and float(row.get("expected_label_purity", 0.0)) >= minimum_purity
    ]


def evaluate(
    input_rows: Sequence[Mapping[str, Any]],
    config: Mapping[str, Any],
    minimum_purity: float,
) -> dict[str, Any]:
    output = process_rows(
        input_rows,
        TemporalStateMachine(config),
    )
    valid = valid_expected_rows(output, minimum_purity)

    if not valid:
        raise ValueError(
            "No valid expected-label rows were found. Check expected_label "
            "and expected_label_purity columns."
        )

    raw_correct = sum(
        row["raw_state"] == row["expected_label"]
        for row in valid
    )
    stable_correct = sum(
        row["stable_state"] == row["expected_label"]
        for row in valid
    )
    false_empty = sum(
        row["stable_state"] == "empty"
        and row["expected_label"] != "empty"
        for row in valid
    )
    false_presence = sum(
        row["stable_state"] != "empty"
        and row["expected_label"] == "empty"
        for row in valid
    )
    accepted = sum(
        bool(row["transition_accepted"])
        for row in output
    )
    inferred = sum(
        bool(row["inferred_transition"])
        for row in output
    )

    return {
        "valid_windows": len(valid),
        "raw_accuracy": raw_correct / len(valid),
        "stable_accuracy": stable_correct / len(valid),
        "accuracy_delta": (
            stable_correct - raw_correct
        ) / len(valid),
        "false_empty_windows": false_empty,
        "false_presence_windows": false_presence,
        "accepted_transitions": accepted,
        "inferred_transitions": inferred,
        "final_stable_state": output[-1]["stable_state"],
    }


def candidate_config(
    smoothing: list[float],
    normal_confirmations: int,
    direct_confirmations: int,
    normal_threshold: float,
    direct_threshold: float,
) -> dict[str, Any]:
    config = copy.deepcopy(DEFAULT_CONFIG)
    config["startup_discard_windows"] = 0
    config["probability_smoothing"][
        "weights_oldest_to_newest"
    ] = list(smoothing)

    for rule in config["normal_transitions"].values():
        rule["confirmations"] = normal_confirmations
        rule["min_target_probability"] = normal_threshold

    for rule in config["direct_transitions"].values():
        rule["enabled"] = True
        rule["confirmations"] = direct_confirmations
        rule["min_target_probability"] = direct_threshold

    return config


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Tune the minimal temporal state machine."
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        required=True,
        help="CSV generated by 01_realtime_inference.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("Tools/datasets/results/state_machine_tuning"),
    )
    parser.add_argument(
        "--minimum-purity",
        type=float,
        default=0.99,
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_rows = read_csv(args.input_csv)

    results: list[dict[str, Any]] = []
    best_config_by_id: dict[str, dict[str, Any]] = {}

    candidate_index = 0
    for smoothing_name, smoothing in SMOOTHING_OPTIONS.items():
        for normal_confirmations in (1, 2):
            for direct_confirmations in (1, 2, 3):
                for normal_threshold in (0.0, 0.50, 0.55):
                    for direct_threshold in (0.0, 0.50, 0.55, 0.60):
                        candidate_index += 1
                        candidate_id = f"candidate_{candidate_index:03d}"
                        config = candidate_config(
                            smoothing=smoothing,
                            normal_confirmations=normal_confirmations,
                            direct_confirmations=direct_confirmations,
                            normal_threshold=normal_threshold,
                            direct_threshold=direct_threshold,
                        )
                        metrics = evaluate(
                            input_rows,
                            config,
                            args.minimum_purity,
                        )
                        row = {
                            "candidate_id": candidate_id,
                            "smoothing": smoothing_name,
                            "normal_confirmations": normal_confirmations,
                            "direct_confirmations": direct_confirmations,
                            "normal_threshold": normal_threshold,
                            "direct_threshold": direct_threshold,
                            **metrics,
                        }
                        results.append(row)
                        best_config_by_id[candidate_id] = config

    results.sort(
        key=lambda row: (
            -float(row["stable_accuracy"]),
            int(row["false_empty_windows"]),
            int(row["false_presence_windows"]),
            int(row["accepted_transitions"]),
            int(row["direct_confirmations"]),
            int(row["normal_confirmations"]),
        )
    )

    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    write_csv(
        output_dir / "state_machine_tuning_results.csv",
        results,
    )

    best = results[0]
    best_config = best_config_by_id[str(best["candidate_id"])]
    best_payload = {
        "schema_version": 4,
        "selection_source": str(args.input_csv),
        "selection_metrics": best,
        "state_machine": best_config,
    }
    with (
        output_dir / "state_machine_config_best.json"
    ).open("w", encoding="utf-8") as file:
        json.dump(
            best_payload,
            file,
            indent=2,
            ensure_ascii=False,
        )

    print()
    print("State Machine Parameter Search")
    print("=" * 72)
    print(f"Candidates evaluated:    {len(results)}")
    print(f"Valid windows:           {best['valid_windows']}")
    print(f"Raw accuracy:            {best['raw_accuracy']:.4f}")
    print(f"Best stable accuracy:    {best['stable_accuracy']:.4f}")
    print(f"Accuracy delta:          {best['accuracy_delta']:+.4f}")
    print(f"False-empty windows:     {best['false_empty_windows']}")
    print(f"False-presence windows:  {best['false_presence_windows']}")
    print(f"Best candidate:          {best['candidate_id']}")
    print(f"Smoothing:               {best['smoothing']}")
    print(
        "Normal confirmations:    "
        f"{best['normal_confirmations']}"
    )
    print(
        "Direct confirmations:    "
        f"{best['direct_confirmations']}"
    )
    print(
        "Normal threshold:        "
        f"{best['normal_threshold']}"
    )
    print(
        "Direct threshold:        "
        f"{best['direct_threshold']}"
    )
    print(
        "Best config:             "
        f"{output_dir / 'state_machine_config_best.json'}"
    )


if __name__ == "__main__":
    main()
